use parsable::Parsable;

use crate::assembler::labels::{Label, LabelLookup};
use crate::assembler::parse::number::LiteralNumber;
use crate::assembler::parse::Ws;
use crate::assembler::parse::token::*;
use crate::instruction::{Condition, Instruction, Register, RegisterPair, RegisterPairIndirect, RegisterPairOrStatus};

#[derive(Clone, Debug, PartialEq, Eq, Parsable)]
pub struct ParsedInstruction {
    inner: ParsedInstructionInner,
}

impl ParsedInstruction {
    pub fn into_inner(self, label_lookup: &LabelLookup) -> Option<Instruction> {
        use Instruction as I;
        use ParsedInstructionInner as PI;
        match self.inner {
            PI::Mov(_, _, r1, _, _, _, r2) => Some(I::Mov(r1, r2)),
            PI::Mvi(_, _, r1, _, _, _, data) => Some(I::Mvi(r1, data.try_into().ok()?)),
            PI::Lxi(_, _, rp, _, data) => Some(I::Lxi(rp, data.try_into().ok()?)),
            PI::Lda(_, _, label) => Some(I::Lda(label_lookup.get(label)?)),
            PI::Sta(_, _, label) => Some(I::Sta(label_lookup.get(label)?)),
            PI::Lhld(_, _, label) => Some(I::Lhld(label_lookup.get(label)?)),
            PI::Shld(_, _, label) => Some(I::Shld(label_lookup.get(label)?)),
            PI::Ldax(_, _, rp) => Some(I::Ldax(rp)),
            PI::Stax(_, _, rp) => Some(I::Stax(rp)),
            PI::Xchg(_) => Some(I::Xchg),

            PI::Add(_, _, r1) => Some(I::Add(r1)),
            PI::Adi(_, _, data) => Some(I::Adi(data.try_into().ok()?)),
            PI::Adc(_, _, r1) => Some(I::Adc(r1)),
            PI::Aci(_, _, data) => Some(I::Aci(data.try_into().ok()?)),
            PI::Sub(_, _, r1) => Some(I::Sub(r1)),
            PI::Sui(_, _, data) => Some(I::Sui(data.try_into().ok()?)),
            PI::Sbb(_, _, r1) => Some(I::Sbb(r1)),
            PI::Sbi(_, _, data) => Some(I::Sbi(data.try_into().ok()?)),
            PI::Inr(_, _, r1) => Some(I::Inr(r1)),
            PI::Dcr(_, _, r1) => Some(I::Dcr(r1)),
            PI::Inx(_, _, rp) => Some(I::Inx(rp)),
            PI::Dcx(_, _, rp) => Some(I::Dcx(rp)),
            PI::Dad(_, _, rp) => Some(I::Dad(rp)),
            PI::Daa(_) => Some(I::Daa),

            PI::Ana(_, _, r1) => Some(I::Ana(r1)),
            PI::Ani(_, _, data) => Some(I::Ani(data.try_into().ok()?)),
            PI::Xra(_, _, r1) => Some(I::Xra(r1)),
            PI::Xri(_, _, data) => Some(I::Xri(data.try_into().ok()?)),
            PI::Ora(_, _, r1) => Some(I::Ora(r1)),
            PI::Ori(_, _, data) => Some(I::Ori(data.try_into().ok()?)),
            PI::Cmp(_, _, r1) => Some(I::Cmp(r1)),
            PI::Cpi(_, _, data) => Some(I::Cpi(data.try_into().ok()?)),
            PI::Rlc(_) => Some(I::Rlc),
            PI::Rrc(_) => Some(I::Rrc),
            PI::Ral(_) => Some(I::Ral),
            PI::Rar(_) => Some(I::Rar),
            PI::Cma(_) => Some(I::Cma),
            PI::Cmc(_) => Some(I::Cmc),
            PI::Stc(_) => Some(I::Stc),

            PI::Jmp(_, _, label) => Some(I::Jmp(label_lookup.get(label)?)),
            PI::Jc(_, _, label) => Some(I::Jcc(Condition::Carry, label_lookup.get(label)?)),
            PI::Jnc(_, _, label) => Some(I::Jcc(Condition::NoCarry, label_lookup.get(label)?)),
            PI::Jz(_, _, label) => Some(I::Jcc(Condition::Zero, label_lookup.get(label)?)),
            PI::Jnz(_, _, label) => Some(I::Jcc(Condition::NoZero, label_lookup.get(label)?)),
            PI::Jp(_, _, label) => Some(I::Jcc(Condition::Positive, label_lookup.get(label)?)),
            PI::Jm(_, _, label) => Some(I::Jcc(Condition::Minus, label_lookup.get(label)?)),
            PI::Jpe(_, _, label) => Some(I::Jcc(Condition::ParityEven, label_lookup.get(label)?)),
            PI::Jpo(_, _, label) => Some(I::Jcc(Condition::ParityOdd, label_lookup.get(label)?)),
            PI::Call(_, _, label) => Some(I::Call(label_lookup.get(label)?)),
            PI::Cc(_, _, label) => Some(I::Ccc(Condition::Carry, label_lookup.get(label)?)),
            PI::Cnc(_, _, label) => Some(I::Ccc(Condition::NoCarry, label_lookup.get(label)?)),
            PI::Cz(_, _, label) => Some(I::Ccc(Condition::Zero, label_lookup.get(label)?)),
            PI::Cnz(_, _, label) => Some(I::Ccc(Condition::NoZero, label_lookup.get(label)?)),
            PI::Cp(_, _, label) => Some(I::Ccc(Condition::Positive, label_lookup.get(label)?)),
            PI::Cm(_, _, label) => Some(I::Ccc(Condition::Minus, label_lookup.get(label)?)),
            PI::Cpe(_, _, label) => Some(I::Ccc(Condition::ParityEven, label_lookup.get(label)?)),
            PI::Cpo(_, _, label) => Some(I::Ccc(Condition::ParityOdd, label_lookup.get(label)?)),
            PI::Ret(_) => Some(I::Ret),
            PI::Rc(_) => Some(I::Rcc(Condition::Carry)),
            PI::Rnc(_) => Some(I::Rcc(Condition::NoCarry)),
            PI::Rz(_) => Some(I::Rcc(Condition::Zero)),
            PI::Rnz(_) => Some(I::Rcc(Condition::NoZero)),
            PI::Rp(_) => Some(I::Rcc(Condition::Positive)),
            PI::Rm(_) => Some(I::Rcc(Condition::Minus)),
            PI::Rpe(_) => Some(I::Rcc(Condition::ParityEven)),
            PI::Rpo(_) => Some(I::Rcc(Condition::ParityOdd)),
            PI::Rst(_, _, data) => Some(I::Rst(data.try_into().ok()?)),
            PI::Pchl(_) => Some(I::Pchl),

            PI::Push(_, _, rp) => Some(I::Push(rp)),
            PI::Pop(_, _, rp) => Some(I::Pop(rp)),
            PI::Xthl(_) => Some(I::Xthl),
            PI::Sphl(_) => Some(I::Sphl),
            PI::Out(_, _, data) => Some(I::Out(data.try_into().ok()?)),
            PI::In(_, _, data) => Some(I::In(data.try_into().ok()?)),
            PI::Ei(_) => Some(I::Ei),
            PI::Di(_) => Some(I::Di),
            PI::Hlt(_) => Some(I::Hlt),
            PI::Nop(_) => Some(I::Nop),
        }
    }

    pub fn instruction_length(&self) -> u16 {
        match self.inner {
            ParsedInstructionInner::Mov(..) => 1,
            ParsedInstructionInner::Mvi(..) => 2,
            ParsedInstructionInner::Lxi(..) => 3,
            ParsedInstructionInner::Lda(..) => 3,
            ParsedInstructionInner::Sta(..) => 3,
            ParsedInstructionInner::Lhld(..) => 3,
            ParsedInstructionInner::Shld(..) => 3,
            ParsedInstructionInner::Ldax(..) => 1,
            ParsedInstructionInner::Stax(..) => 1,
            ParsedInstructionInner::Xchg(..) => 1,
            ParsedInstructionInner::Add(..) => 1,
            ParsedInstructionInner::Adi(..) => 2,
            ParsedInstructionInner::Adc(..) => 1,
            ParsedInstructionInner::Aci(..) => 2,
            ParsedInstructionInner::Sub(..) => 1,
            ParsedInstructionInner::Sui(..) => 2,
            ParsedInstructionInner::Sbb(..) => 1,
            ParsedInstructionInner::Sbi(..) => 2,
            ParsedInstructionInner::Inr(..) => 1,
            ParsedInstructionInner::Dcr(..) => 1,
            ParsedInstructionInner::Inx(..) => 1,
            ParsedInstructionInner::Dcx(..) => 1,
            ParsedInstructionInner::Dad(..) => 1,
            ParsedInstructionInner::Daa(..) => 1,
            ParsedInstructionInner::Ana(..) => 1,
            ParsedInstructionInner::Ani(..) => 2,
            ParsedInstructionInner::Xra(..) => 1,
            ParsedInstructionInner::Xri(..) => 2,
            ParsedInstructionInner::Ora(..) => 1,
            ParsedInstructionInner::Ori(..) => 2,
            ParsedInstructionInner::Cmp(..) => 1,
            ParsedInstructionInner::Cpi(..) => 2,
            ParsedInstructionInner::Rlc(..) => 1,
            ParsedInstructionInner::Rrc(..) => 1,
            ParsedInstructionInner::Ral(..) => 1,
            ParsedInstructionInner::Rar(..) => 1,
            ParsedInstructionInner::Cma(..) => 1,
            ParsedInstructionInner::Cmc(..) => 1,
            ParsedInstructionInner::Stc(..) => 1,
            ParsedInstructionInner::Jmp(..) => 3,
            ParsedInstructionInner::Jc(..) => 3,
            ParsedInstructionInner::Jnc(..) => 3,
            ParsedInstructionInner::Jz(..) => 3,
            ParsedInstructionInner::Jnz(..) => 3,
            ParsedInstructionInner::Jp(..) => 3,
            ParsedInstructionInner::Jm(..) => 3,
            ParsedInstructionInner::Jpe(..) => 3,
            ParsedInstructionInner::Jpo(..) => 3,
            ParsedInstructionInner::Call(..) => 3,
            ParsedInstructionInner::Cc(..) => 3,
            ParsedInstructionInner::Cnc(..) => 3,
            ParsedInstructionInner::Cz(..) => 3,
            ParsedInstructionInner::Cnz(..) => 3,
            ParsedInstructionInner::Cp(..) => 3,
            ParsedInstructionInner::Cm(..) => 3,
            ParsedInstructionInner::Cpe(..) => 3,
            ParsedInstructionInner::Cpo(..) => 3,
            ParsedInstructionInner::Ret(..) => 1,
            ParsedInstructionInner::Rc(..) => 1,
            ParsedInstructionInner::Rnc(..) => 1,
            ParsedInstructionInner::Rz(..) => 1,
            ParsedInstructionInner::Rnz(..) => 1,
            ParsedInstructionInner::Rp(..) => 1,
            ParsedInstructionInner::Rm(..) => 1,
            ParsedInstructionInner::Rpe(..) => 1,
            ParsedInstructionInner::Rpo(..) => 1,
            ParsedInstructionInner::Rst(..) => 1,
            ParsedInstructionInner::Pchl(..) => 1,
            ParsedInstructionInner::Push(..) => 1,
            ParsedInstructionInner::Pop(..) => 1,
            ParsedInstructionInner::Xthl(..) => 1,
            ParsedInstructionInner::Sphl(..) => 1,
            ParsedInstructionInner::In(..) => 2,
            ParsedInstructionInner::Out(..) => 2,
            ParsedInstructionInner::Ei(..) => 1,
            ParsedInstructionInner::Di(..) => 1,
            ParsedInstructionInner::Hlt(..) => 1,
            ParsedInstructionInner::Nop(..) => 1,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Parsable)]
enum ParsedInstructionInner {
    Mov(Mov, Ws, Register, Ws, Comma, Ws, Register),
    Mvi(Mvi, Ws, Register, Ws, Comma, Ws, LiteralNumber),
    Lxi(Lxi, Ws, RegisterPair, Ws, LiteralNumber),
    Lda(Lda, Ws, Label),
    Sta(Sta, Ws, Label),
    Lhld(Lhld, Ws, Label),
    Shld(Shld, Ws, Label),
    Ldax(Ldax, Ws, RegisterPairIndirect),
    Stax(Stax, Ws, RegisterPairIndirect),
    Xchg(Xchg),

    Add(Add, Ws, Register),
    Adi(Adi, Ws, LiteralNumber),
    Adc(Adc, Ws, Register),
    Aci(Aci, Ws, LiteralNumber),
    Sub(Sub, Ws, Register),
    Sui(Sui, Ws, LiteralNumber),
    Sbb(Sbb, Ws, Register),
    Sbi(Sbi, Ws, LiteralNumber),
    Inr(Inr, Ws, Register),
    Dcr(Dcr, Ws, Register),
    Inx(Inx, Ws, RegisterPair),
    Dcx(Dcx, Ws, RegisterPair),
    Dad(Dad, Ws, RegisterPair),
    Daa(Daa),

    Ana(Ana, Ws, Register),
    Ani(Ani, Ws, LiteralNumber),
    Xra(Xra, Ws, Register),
    Xri(Xri, Ws, LiteralNumber),
    Ora(Ora, Ws, Register),
    Ori(Ori, Ws, LiteralNumber),
    Cmp(Cmp, Ws, Register),
    Cpi(Cpi, Ws, LiteralNumber),
    Rlc(Rlc),
    Rrc(Rrc),
    Ral(Ral),
    Rar(Rar),
    Cma(Cma),
    Cmc(Cmc),
    Stc(Stc),

    Jmp(Jmp, Ws, Label),
    Jc(Jc, Ws, Label),
    Jnc(Jnc, Ws, Label),
    Jz(Jz, Ws, Label),
    Jnz(Jnz, Ws, Label),
    Jp(Jp, Ws, Label),
    Jm(Jm, Ws, Label),
    Jpe(Jpe, Ws, Label),
    Jpo(Jpo, Ws, Label),
    Call(Call, Ws, Label),
    Cc(Cc, Ws, Label),
    Cnc(Cnc, Ws, Label),
    Cz(Cz, Ws, Label),
    Cnz(Cnz, Ws, Label),
    Cp(Cp, Ws, Label),
    Cm(Cm, Ws, Label),
    Cpe(Cpe, Ws, Label),
    Cpo(Cpo, Ws, Label),
    Ret(Ret),
    Rc(Rc),
    Rnc(Rnc),
    Rz(Rz),
    Rnz(Rnz),
    Rp(Rp),
    Rm(Rm),
    Rpe(Rpe),
    Rpo(Rpo),
    Rst(Rst, Ws, LiteralNumber),
    Pchl(Pchl),

    Push(Push, Ws, RegisterPairOrStatus),
    Pop(Pop, Ws, RegisterPairOrStatus),
    Xthl(Xthl),
    Sphl(Sphl),
    In(In, Ws, LiteralNumber),
    Out(Out, Ws, LiteralNumber),
    Ei(Ei),
    Di(Di),
    Hlt(Hlt),
    Nop(Nop),
}
